komga:
  baseUri: "http://komga:25600"
  komgaUser: "admin@manga.local"
  komgaPassword: "changeme"
  eventListener:
    enabled: true
    libraries: []
  metadataUpdate:
    default:
      aggregate: true
      bookCovers: true
      seriesCovers: true
      overrideExistingCovers: false
      updateModes:
        - API
      postProcessing:
        seriesTitle: true
        titleType: LOCALIZED
  providers:
    mangaUpdates:
      enabled: true
      priority: 10
    myAnimeList:
      enabled: true
      priority: 20
    aniList:
      enabled: true
      priority: 30

database:
  file: /config/database.sqlite
